# Generated by Django 5.2.11 on 2026-05-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('efrontend', '0003_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosetting',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_settings', to='company.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='company.company'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_locations', to='company.company'),
        ),
    ]
