# Generated by Django 5.2.11 on 2026-05-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
