# Generated by Django 5.2.11 on 2026-05-14 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_email',
            field=models.EmailField(blank=True, help_text='Admin login email', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='admin_name',
            field=models.CharField(blank=True, help_text='Admin display name', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='admin_password',
            field=models.CharField(blank=True, help_text='Admin login password', max_length=128),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
