# Generated by Django 5.2.11 on 2026-05-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='domain_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
