# Generated by Django 5.2.11 on 2026-04-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_firebase_uid_myuser_is_admin_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='cart_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='wishlist_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
