# Generated by Django 5.2.11 on 2026-05-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company_address_company_phone'),
        ('account', '0002_initial'),
    ]

    operations = [
    ]
