# Generated by Django 5.2.11 on 2026-05-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='msg_type',
            field=models.CharField(blank=True, default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(blank=True, default='sent', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_name',
            field=models.CharField(blank=True, default='Guest', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='component',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='contact_channel',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='current_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='model',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='service_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='serviceticket',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('assistant', 'Assistant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
